### ISSUE TITLE
DetachedCriteria does not generate valid SQL when Left Outer Join used and multiple level navigation

### ISSUE THREAD

**Issue by danielpalacian** [nhibernate/nhibernate-core#3211] opened 2022-12-19 08:12 UTC
Hello. 
I inherited a system that uses DetachedCriteria to generate queries against SQL. 
Recently i tried to migrate this project from version 3.3.3.4001 to version 5.4.0. 
After the upgrade some old functionality of the DetachedCriteria does not work as before. 

I have the following DB Structure.   Product with a FK to Category and this with a FK to CategoryType.

 Sample code: 
 
           Type entityType = Type.GetType(typeof(Product).AssemblyQualifiedName);

            var criteria = DetachedCriteria.For(entityType, "t6_0");
            criteria.CreateAlias("Category", "t6_1", NHibernate.SqlCommand.JoinType.LeftOuterJoin);
            criteria.CreateAlias("Category.CategoryType", "t6_2", NHibernate.SqlCommand.JoinType.LeftOuterJoin);

            ICriterion criterion = Restrictions.Eq(Projections.Property("t6_2.id"), 3);
            var nhibJunction = Restrictions.Conjunction();
            nhibJunction.Add(criterion);

            criteria.Add(nhibJunction);

            criteria.SetProjection(Projections.Id());

            var result =  criteria.GetExecutableCriteria(session).List();
            
            
  Generated sql is : 
         SELECT
         this_.Id AS y0_
            FROM
                    Product this_
            LEFT OUTER JOIN
                    Category t6_1x1_
            ON
                    this_.FK_Category_Id=t6_1x1_.Id
            WHERE  ( t6_2x2_.Id = @p0)
            
  SO the Left Outher join with CategoryType is missing. 
  
  In version 3.3.3.4001 the generated sql is valid. 
   
  Is this something not supported anymore? 
  Is there a workaround? 
  Thx in advance.

**Comment by bahusoid** [comment] 2022-12-19 08:30
Duplicate of #2185 

Workaround is to use created alias for `Category`

```C#
criteria.CreateAlias("Category", "t6_1", NHibernate.SqlCommand.JoinType.LeftOuterJoin);
criteria.CreateAlias("t6_1.CategoryType", "t6_2", NHibernate.SqlCommand.JoinType.LeftOuterJoin);
```

**Closed by bahusoid** 2022-12-19 08:30 UTC
