### ISSUE TITLE
Lazy loading of collections with wrong case in key - different behaviour using Get vs Query?

### ISSUE THREAD

**Issue by nicklascarlsson** [nhibernate/nhibernate-core#1828] opened 2018-08-21 11:33 UTC
I'm receiving a request from another system where the key of an entity has the **wrong case** 
(e.g. Id = 'ABC', where it should be Id = 'Abc').

Fetching the entity from our database works fine, but regarding lazy loading of related collections I run into problems.

Seems like I get different behaviour when using 
**Session.Get<T>('ABC')**, vs 
**Session.Query<T>(x => x.Id == 'ABC').SingleOrDefault()**

When trying to fetch the related collection with Get (mapped as a Bag) into an IList, the collection isn't loaded. I can see in NHibernate Profiler that the sql query is run and 5 records are found, but the list remains empty.

When using Query, the sql query is run and the list is populated though.

I've check in earlier releases that we use (3.3.3.4001, 4.1.1.4000 and 5.1.1) and found the same behaviour.
Anyone have experienced the same behaviour, is there a logical explanation to this perhaps?

Regards
// Nicklas

**Comment by fredericDelaporte** [comment] 2018-08-21 21:43
It seems to me this trouble is already reported somewhere, but I am not finding it...

**Comment by hazzik** [comment] 2018-08-21 21:43
Try JIRA

**Comment by fredericDelaporte** [comment] 2018-08-21 21:54
I had searched there too.

**Comment by nicklascarlsson** [comment] 2018-08-22 13:39
After some searching I found this:
[https://nhibernate.jira.com/browse/NH-3833](url)
Is this the one you are thinking about @fredericDelaporte ?

The difference, I feel, is that I get different behaviour between Get and Query.
And in the latter, it actually works regardless of case.. :)

**Comment by fredericDelaporte** [comment] 2018-08-22 15:02
Indeed, it is not the same but related. The suggested solution in this Jira should work here too.

I guess that when using `Get` (and likely `Load` too), the id gets hydrated with the supplied argument, instead of being read from the database. The database being case insensitive in your case, it returns an entity, but probably hydrated by NHibernate with the wrongly cased identifier, causing later NHibernate to discard collection children having the right casing as foreign key, because comparison of string in .Net are case sensitive by default.

String types in NHibernate use the default comparison. So for solving this mismatch between comparisons in database and comparison in NHibernate, you need to map your identifier with a custom type having a case insensitive equality.

The query case works because it hydrates the identifier from the database, not from the wrongly cased supplied argument.

Still I do not find it very satisfying to not have a way to handle how string comparisons should be performed at the type level, forcing users to define their own string type for handling that when the default .Net comparison does not suit their needs. Maybe some improvements could be done here.

But this trouble is likely not so common, because using case insensitive strings as primary keys is likely not a popular pattern either.

**Comment by fredericDelaporte** [comment] 2018-08-27 11:47
I can confirm that using a type overriding `IsEqual(object x, object y)` and `GetHashcode(object x)` for being case insensitive solves the issue. (See 3edda1d; this a commit on a private branch, I have not made a PR of it yet.)

So, I am closing this as external, a custom type is to be used for supporting this case currently.

(I may submit a PR from 3edda1d, but I am not convinced yet it is a suitable solution.)

**Closed by fredericDelaporte** 2018-08-27 11:47 UTC

**Comment by hazzik** [comment] 2018-08-27 11:54
@fredericDelaporte I think we could, potentially, add an option to allow string types behaving according to this option. Similar to timespan, varchar2 for oracle, etc

**Comment by fredericDelaporte** [comment] 2018-08-27 12:29
If you are thinking about a dialect option (varchar2 is handled through an Oracle dialect option), there is a number of cases which do call `IsEqual(object x, object y)` instead of `IsEqual(object x, object y, ISessionFactoryImplementor factory)`, but only the later would be able to handle the option.

An alternate solution is also 8a87ec9.

3edda1d does add `Ci` string types. This is similar to what has been done for UTC/local date types, but well, I dislike this way of duplicating types for handling variations in behavior.

8a87ec9 allows to directly globally set the comparer to use for string types. It avoids duplicating the string types and allows using a specific culture, but that is a static property. There is no way to mix behaviors in the same mapping with this solution.

A third way could be to implement `IParameterizedType` on `AbstractStringType` and handle type parameters specifying the culture or the case sensitivity. But it is not very convenient to specify type parameters in mappings. It could be mixed with 8a87ec9.

**Comment by nicklascarlsson** [comment] 2018-08-28 08:57
Thanks for your effort on this @fredericDelaporte and @hazzik ! =)

I decided to refactor and not use string as primary key for the entity.
I've thought about it for some time, so maybe it is worth the work!

Thanks and regards

/Nicklas

**Comment by fredericDelaporte** [comment] 2018-09-16 10:11
#1833 will provide a built-in way of handling this case, with NHibernate v5.2.

**Comment by nicklascarlsson** [comment] 2018-09-19 11:04
Great news! Many thanks @fredericDelaporte :-)
