### ISSUE TITLE
Microsoft.Data.SqlClient  and  System.Data.SqlClient 

### ISSUE THREAD

**Issue by jiaxiang8756** [nhibernate/nhibernate-core#2332] opened 2020-03-20 02:18 UTC
When using CAP, I throw an exception: Unable to cast object of type 'System.Data.SqlClient.SqlConnection' to type 'Microsoft.Data.SqlClient.SqlConnection'. I found that CAP uses Microsoft.Data. SqlClient. How to solve it?

**Comment by hazzik** [comment] 2020-03-20 07:48
First of all what is CAP?

**Comment by jiaxiang8756** [comment] 2020-03-21 02:58
https://github.com/dotnetcore/CAP

**Comment by jiaxiang8756** [comment] 2020-03-21 02:59
> 首先，CAP是什么？

https://github.com/dotnetcore/CAP

**Comment by mashbrno** [comment] 2020-03-23 07:36
Maybe just wait for 5.3 release where #2216 is implemented

**Comment by jiaxiang8756** [comment] 2020-03-23 07:47
> 也许只是等待5.3版本，其中[＃2216](https://github.com/nhibernate/nhibernate-core/pull/2216)中实现

Thanks！

**Comment by jiaxiang8756** [comment] 2020-03-23 07:48
> Maybe just wait for 5.3 release where #2216 is implemented

Thanks！

**Comment by queil** [comment] 2020-03-26 16:17
@mashbrno When is 5.3 release planned for? I was trying to find it with no success.

**Comment by fredericDelaporte** [comment] 2020-03-26 20:48
Well, it's been a long time since the last minor release, but we have quite a few PR which would be nice to finish before releasing 5.3.
We do not have a fixed schedule on releases.
If you want to try its current state, you may go to [master commits](https://github.com/nhibernate/nhibernate-core/commits/master), check there the last builds (green check mark usually), from ther go to the Teamcity build "Release Package", log in (as guest if you do not have an account), go to artifacts tab and get the binaries (NuGet package for all targets, or only for the .Net Framework, there is a zip).

**Comment by hazzik** [comment] 2020-04-18 20:20
Duplicate of #2216

**Closed by hazzik** 2020-04-18 20:20 UTC
Labels: r: Duplicate, r: Not an Issue
