### ISSUE TITLE
Odata expand not working on collections

### ISSUE THREAD

**Issue by manureini** [nhibernate/nhibernate-core#2991] opened 2022-01-16 01:44 UTC
Hello,

I'm using NHibernate `5.3.10` and Microsoft.AspNetCore.OData `8.0.6` and I try to run the following query:

`http://localhost:5237/odata/School?$expand=Students`

Instead of getting the result the following exception is raised:

<details>
  <summary>System.ArgumentException: Argument types do not match</summary>

  ```csharp
System.ArgumentException: Argument types do not match
   at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse)
   at NHibernate.Linq.ReWriters.SubQueryConditionalExpander.SubQueryFromClauseExpander.VisitConditional(ConditionalExpression node)
   at NHibernate.Linq.ReWriters.SubQueryConditionalExpander.SubQueryConditionalExpressionExpander.VisitSubQuery(SubQueryExpression expression)
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at Remotion.Linq.Clauses.SelectClause.TransformExpressions(Func`2 transformation)
   at NHibernate.Linq.ReWriters.SubQueryConditionalExpander.SubQueryConditionalExpressionExpander.Transform(IClause clause)
   at NHibernate.Linq.ReWriters.SubQueryConditionalExpander.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at NHibernate.Linq.ReWriters.SubQueryConditionalExpander.ReWrite(QueryModel queryModel)
   at NHibernate.Linq.Visitors.QueryModelVisitor.GenerateHqlQuery(QueryModel queryModel, VisitorParameters parameters, Boolean root, Nullable`1 rootReturnType)
   at NHibernate.Linq.NhLinqExpression.Translate(ISessionFactoryImplementor sessionFactory, Boolean filter)
   at NHibernate.Hql.Ast.ANTLR.ASTQueryTranslatorFactory.CreateQueryTranslators(IQueryExpression queryExpression, String collectionRole, Boolean shallow, IDictionary`2 filters, ISessionFactoryImplementor factory)
   at NHibernate.Engine.Query.QueryPlanCache.GetHQLQueryPlan(IQueryExpression queryExpression, Boolean shallow, IDictionary`2 enabledFilters)
   at NHibernate.Impl.AbstractSessionImpl.GetHQLQueryPlan(IQueryExpression queryExpression, Boolean shallow)
   at NHibernate.Impl.AbstractSessionImpl.CreateQuery(IQueryExpression queryExpression)
   at NHibernate.Linq.DefaultQueryProvider.PrepareQuery(Expression expression, IQuery& query)
   at NHibernate.Linq.DefaultQueryProvider.ExecuteList[TResult](Expression expression)
   at NHibernate.Linq.NhQueryable`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.OData.Routing.ODataRouteDebugMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

  ```
  
</details>

I played around with the .net6 `NHibernate.Test` Project, but I was not able to create a according unittest - Sorry 😞 
Because of that I created a small project to reproduce this issue:

https://github.com/manureini/OdataTestNhibernate/tree/main

It would be great to get feedback if this is a bug in nhibernate or I'm just doing something wrong 😊
Other features like $filter are working fine.

Thanks!

**Comment by RodrigoRodriguesX10** [comment] 2022-01-25 22:34
In your example project you not mapping the relation between school and student. I think you need to add the School property and map the schoolId foreign key column. 
```xml
		<set name="Students">
			<key column="SchoolId"/>
			<one-to-many class="Student"/>
		</set>
```

The column="SchoolId" must exists in Student mapping.

**Comment by bahusoid** [comment] 2022-02-16 11:10
It doesn't look like NHibernate issue. Most likely some configuration/mapping issue.

We do have `expand` ODATA tests and everything works OK. See https://github.com/nhibernate/nhibernate-core/blob/502d2438df35de73e4dc453cf75055806efa949b/src/NHibernate.Test/Linq/ODataTests.cs#L28-L41

**Comment by manureini** [comment] 2022-04-10 17:57
@bahusoid  It is a NHibernate issue.

In my testproject the Expression from odata looks like this:

<details>


 ```
.Call System.Linq.Queryable.Select(
    .Constant<NHibernate.Linq.NhQueryable`1[OdataTestNhibernate.Models.School]>(NHibernate.Linq.NhQueryable`1[OdataTestNhibernate.Models.School]),
    '(.Lambda #Lambda1<System.Func`2[OdataTestNhibernate.Models.School,Microsoft.AspNetCore.OData.Query.Wrapper.SelectAllAndExpand`1[OdataTestNhibernate.Models.School]]>))

.Lambda #Lambda1<System.Func`2[OdataTestNhibernate.Models.School,Microsoft.AspNetCore.OData.Query.Wrapper.SelectAllAndExpand`1[OdataTestNhibernate.Models.School]]>(OdataTestNhibernate.Models.School $$it)
{
    .New Microsoft.AspNetCore.OData.Query.Wrapper.SelectAllAndExpand`1[OdataTestNhibernate.Models.School](){
        Model = .Constant<Microsoft.AspNetCore.OData.Query.Container.LinqParameterContainer+TypedLinqParameterContainer`1[Microsoft.OData.Edm.IEdmModel]>(Microsoft.AspNetCore.OData.Query.Container.LinqParameterContainer+TypedLinqParameterContainer`1[Microsoft.OData.Edm.IEdmModel]).TypedProperty,
        Instance = $$it,
        UseInstanceForProperties = True,
        Container = .New Microsoft.AspNetCore.OData.Query.Container.NamedProperty`1[System.Collections.Generic.IEnumerable`1[Microsoft.AspNetCore.OData.Query.Wrapper.SelectAll`1[OdataTestNhibernate.Models.Student]]]()
        {
            Name = "Students",
            Value = .If (.If ($$it == null) {
                null
            } .Else {
                $$it.Students
            } == null) {
                null
            } .Else {
                .Call System.Linq.Enumerable.Select(
                    .If ($$it == null) {
                        null
                    } .Else {
                        $$it.Students
                    },
                    .Lambda #Lambda2<System.Func`2[OdataTestNhibernate.Models.Student,Microsoft.AspNetCore.OData.Query.Wrapper.SelectAll`1[OdataTestNhibernate.Models.Student]]>)
            }
        }
    }
}

.Lambda #Lambda2<System.Func`2[OdataTestNhibernate.Models.Student,Microsoft.AspNetCore.OData.Query.Wrapper.SelectAll`1[OdataTestNhibernate.Models.Student]]>(OdataTestNhibernate.Models.Student $$it)
{
    .New Microsoft.AspNetCore.OData.Query.Wrapper.SelectAll`1[OdataTestNhibernate.Models.Student](){
        Model = .Constant<Microsoft.AspNetCore.OData.Query.Container.LinqParameterContainer+TypedLinqParameterContainer`1[Microsoft.OData.Edm.IEdmModel]>(Microsoft.AspNetCore.OData.Query.Container.LinqParameterContainer+TypedLinqParameterContainer`1[Microsoft.OData.Edm.IEdmModel]).TypedProperty,
        Instance = $$it,
        UseInstanceForProperties = True
    }
}
```
 
</details>

It contains a `SelectAllAndExpand` Wrapper which is not present in the NHibernate unittests.

The issue is in `SubQueryFromClauseExpander` Method `VisitConditional` (or deeper in the code). 

https://github.com/nhibernate/nhibernate-core/blob/47992e73ed6114093f31ed99829dd8c4c7663829/src/NHibernate/Linq/ReWriters/SubQueryConditionalExpander.cs#L118

This creates a `newFalse` Expression which have a different `Type` than the `newTrue` Expression.

A short hack to workaroud this issue can be added after the referenced code above (I assume it's not the right line to fix the issue here, but for demonstration).

```csharp
	if (newFalse.Type != newTrue.Type && newTrue is ConstantExpression constantExpr)
	{
		newTrue = Expression.Constant(constantExpr.Value, newFalse.Type);
	}
```

After also fixing my mapping issue (thank you @RodrigoRodriguesX10) and with this hack, I'll get an odata result,
 **BUT it contains multiple values of the same Student** which is also wrong in my opinion.

It would be nice, if you can look at this issue. Thanks ;)

**Comment by andreyciocan** [comment] 2023-02-12 14:34
I am having the same issue with NHibernate 5.4.1... Also @manureini I have tried to run your project and the same error occurs: Argument type mismatch. Any hints on how to solve this?

**Comment by manureini** [comment] 2023-02-12 16:56
@andreyciocan Sorry, nope. I've switched to ef.

**Comment by andreyciocan** [comment] 2023-02-12 18:23
@manureini thank you for your quick response... at least I know to not spend more hours trying different approaches... @bahusoid can you please check again on this and maybe consider it an issue? Or at least point us the right way to configure this case? Many thanks in advance

**Comment by bahusoid** [comment] 2023-02-13 08:38
Does it fail the same with v7 (Microsoft.AspNetCore.OData v7.6.3)?

**Comment by andreyciocan** [comment] 2023-02-13 09:16
@bahusoid same issue on OData v7:
Here is the stack trace:
System.ArgumentException: Argument types do not match
   at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at NHibernate.Linq.ReWriters.SubQueryConditionalExpander.SubQueryConditionalExpressionExpander.VisitSubQuery(SubQueryExpression expression)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Clauses.SelectClause.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at NHibernate.Linq.Visitors.QueryModelVisitor.GenerateHqlQuery(QueryModel queryModel, VisitorParameters parameters, Boolean root, Nullable`1 rootReturnType)
   at NHibernate.Linq.NhLinqExpression.Translate(ISessionFactoryImplementor sessionFactory, Boolean filter)
   at NHibernate.Hql.Ast.ANTLR.ASTQueryTranslatorFactory.CreateQueryTranslators(IQueryExpression queryExpression, String collectionRole, Boolean shallow, IDictionary`2 filters, ISessionFactoryImplementor factory)
   at NHibernate.Engine.Query.QueryPlanCache.GetHQLQueryPlan(IQueryExpression queryExpression, Boolean shallow, IDictionary`2 enabledFilters)
   at NHibernate.Impl.AbstractSessionImpl.GetHQLQueryPlan(IQueryExpression queryExpression, Boolean shallow)
   at NHibernate.Impl.AbstractSessionImpl.CreateQuery(IQueryExpression queryExpression)
   at NHibernate.Linq.DefaultQueryProvider.PrepareQuery(Expression expression, IQuery& query)
   at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
   at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.System.Collections.IEnumerable.GetEnumerator()
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSetAsync(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectAsync(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStreamAsync(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()

**Comment by bahusoid** [comment] 2023-02-13 11:04
Try with `HandleNullPropagationOption.False` in `ODataQuerySettings.HandleNullPropagation` as it's done it our tests.

Please check other ODATA settings done in our tests:
https://github.com/nhibernate/nhibernate-core/blob/502d2438df35de73e4dc453cf75055806efa949b/src/NHibernate.Test/Linq/ODataTests.cs#L92-L115

**Comment by andreyciocan** [comment] 2023-02-13 11:18
@bahusoid Setting HandleNullPropagationOption.False is working as expected. I have done this on [EnableQuery] attribute:
`[EnableQuery(HandleNullPropagation = HandleNullPropagationOption.False)]`

Thank you for your support and quick response. You saved my day,

**Comment by bahusoid** [comment] 2023-02-13 11:41
Duplicate of #1320

**Closed by bahusoid** 2023-02-13 11:41 UTC
