### ISSUE TITLE
Cannot map a class multiple times with EntityName using NH mapping-by-code

### ISSUE THREAD

**Issue by billpoole-mi** [nhibernate/nhibernate-core#2095] opened 2019-04-01 04:05 UTC
We find that if we provide two mappings for the same class by invoking EntityName(string) in mapping by code, the second class definition replaces the first. I suspect this means that class mappings are indexed by type, which is ignoring the entity name, if specified.

For example, consider the mapping code below:

```csharp
public class ParentMapping : ClassMapping<Parent>
{
    public ParentMapping()
    {
        Table("parent");

        Id(c => c.Id, id =>
        {
            id.Access(Accessor.Property);
            id.Generator(Generators.HighLow);
        });

        Property(c => c.Name, p =>
        {
            p.Access(Accessor.Property);
            p.NotNullable(true);
        });

        Set(c => c.Children, m =>
        {
            m.Access(Accessor.Property);
            m.Key(c => c.Column("ParentId"));
            m.Inverse(true);
        }, m =>
        {
            m.OneToMany(oneToMany => oneToMany.EntityName("ChildEntity"));
        });
    }
}

public class ChildMapping : ClassMapping<Child>
{
    public ChildMapping()
    {
        EntityName("ChildEntity");
        Table("child");

        Id(mr => mr.Id, id =>
        {
            id.Access(Accessor.Property);
            id.Generator(Generators.HighLow);
        });

        Property(c => c.Name, p =>
        {
            p.Access(Accessor.Property);
            p.NotNullable(true);
        });

        ManyToOne(c => c.Parent, mapping =>
        {
            mapping.Access(Accessor.Property);
            mapping.Column("ParentId");
        });
    }
}

public class ChildMapping2 : ClassMapping<Child>
{
    public ChildMapping2()
    {
        EntityName("ChildEntity2");
        Table("child2");

        Id(mr => mr.Id, id =>
        {
            id.Access(Accessor.Property);
            id.Generator(Generators.HighLow);
        });

        Property(c => c.Name, p =>
        {
            p.Access(Accessor.Property);
            p.NotNullable(true);
        });

        ManyToOne(c => c.Parent, mapping =>
        {
            mapping.Access(Accessor.Property);
            mapping.Column("ParentId");
        });
    }
}
```

We find that when building the session factory, NHibernate throws an exception saying that entity "ChildEntity" is unrecognized. However, if we delete the ChildMapping2 class, then NHibernate works as expected.

**Comment by hazzik** [comment] 2019-04-01 04:16
Duplicate of #1157

**Closed by hazzik** 2019-04-01 04:16 UTC
