### ISSUE TITLE
Linq left join DefaultIfEmptyResultOperator not supported

### ISSUE THREAD

**Issue by Kerdanite** [nhibernate/nhibernate-core#2243] opened 2019-10-09 15:23 UTC
I'm using LINQ  with NHibernate version 5.2.6.

I want to make a left join using Linq to a not mapped properties.

```
this.Session.Query<Container>()
.Join(this.Session.Query<ViewContainerInfo>(r => r.Id, v => v.ContainerId, (c, v) => new {
Container = c,
ContainerInfo = v
}).DefaultIfEmpty();
```
This result on an exception The DefaultIfEmptyResultOperator result operator is not current supported.

What i want to perform is an sql like
```
SELECT c.*, ci.*
FROM Container C
LEFT JOIN ViewContainerInfo ci on ci.ContainerId = c.Id
```
ContainerInfo is a view, so i don't have navigation properties in my Container Entity.

**Comment by hazzik** [comment] 2019-10-09 21:04
Duplicate of #864

**Closed by hazzik** 2019-10-09 21:04 UTC
