### ISSUE TITLE
Lazy loading and Eager initialization for Component

### ISSUE THREAD

**Issue by megafetis** [nhibernate/nhibernate-core#1861] opened 2018-09-28 14:53 UTC
For example:
```csharp
class Organization
{
    public virtual string Name {get;set;}
    public virtual Address Address {get;set;}
}
class Address
{
    public virtual string City {get;set;}
    public virtual Address Street {get;set;}
}

protected OrganizationMap()
{
    Id(p => p.Id).GeneratedBy.UuidHex("N").Length(32);
    Component(p => p.Address, a =>
    {
        a.LazyLoad();
        a.ColumnPrefix("adr_");
        a.Map(p => p.Street);
        a.Map(p => p.City);
    });   
    Map(p => p.Name).Not.Nullable();
}

var orgs = nHsession.QueryOver<Organization>().Fetch(p=>p.Address).Eager.List();
```
Please add feature to Eager load mapped as Component properties

**Comment by fredericDelaporte** [comment] 2018-10-12 10:41
#1599 will provide a way to fetch entities with their lazy properties. Will it be enough?

**Comment by megafetis** [comment] 2018-10-12 14:09
That would be great, to implement partial eager initialization of model. 
For example, we have some lazy properties or components. 
Adding possibility to selectively (optionally) eager load some of these properties.

I see, that now is possible to load ALL lazy properties immediately

**Comment by megafetis** [comment] 2018-10-12 14:12
Example:
3) SelectMode.FetchLazyProperties you can fetch entities with lazy properties initialized:
4) SelectMode.FetchLazyProperty !!!
`var root = session.QueryOver<EntityComplex>()
			.Fetch(SelectMode.FetchLazyProperty, ec => ec.SomeProperty1)
                        .Fetch(SelectMode.FetchLazyProperty, ec => ec.SomeProperty2)
			.Where(ec => ec.LazyProp != null)
			.Take(1)
			.SingleOrDefault();`

**Comment by fredericDelaporte** [comment] 2018-10-12 14:37
Yes, currently, loading lazy properties is an all or nothing process (excepted for lazy many-to-one or lazy collections, which have their own loaders and are loaded separately).

There is no way to load only some of the lazy properties, excepted using some projections to a custom DTO (but then, it is no more an entity loading).

There are some old todo in the code about handling property groups for loading only part of them, but it seems far from being done.

**Comment by megafetis** [comment] 2018-10-12 17:08
Its a pity. But I want to thank you about very useful and favorite library Nhibernate

**Comment by fredericDelaporte** [comment] 2018-10-12 18:05
You should leave it open if you wish someone to maybe have a look into implementing this some days.

**Comment by megafetis** [comment] 2018-10-12 18:44
Ok thanks

**Comment by hazzik** [comment] 2018-10-13 05:12
This is a duplicate of #1031

**Comment by hazzik** [comment] 2018-10-13 05:12
Duplicate of #1031

**Comment by hazzik** [comment] 2018-10-13 05:20
Actually, let's make opposite.

**Comment by hazzik** [comment] 2018-10-13 05:21
Never mind. Let's treat these issues separately.

**Closed** 2020-02-20 18:04 UTC
Labels: c: QueryOver, p: Minor, t: New Feature
