### ISSUE TITLE
Error when query with delayed insert entity in where expression

### ISSUE THREAD

**Issue by galamai** [nhibernate/nhibernate-core#2414] opened 2020-06-06 12:50 UTC
Hi,
Throw System.InvalidCastException: Unable to cast object of type 'NHibernate.Action.DelayedPostInsertIdentifier' to type 'System.IConvertible'

```
    var entity = new Entity();
    session.Persist(entity);
    var entities= session.Query<Entity>().Where(x => x == entity).ToList();
```

**Comment by bahusoid** [comment] 2020-06-09 08:07
So to make this query work session `Flush` is required. Isn't it? Did you change default flush mode level (`default_flush_mode`)? In theory it should work with `FlushMode.Auto` level..

**Comment by galamai** [comment] 2020-06-09 09:33
I use FlushMode.Commit and with FlushMode.Auto throw System.InvalidCastException. For fixing it need update this method on NHibernate.Type.NullableType:
```
                public sealed override void NullSafeSet(DbCommand st, object value, int index, ISessionImplementor session)
		{
			if (value == null)
			{
				if (IsDebugEnabled)
				{
					Log.Debug("binding null to parameter: {0}", index);
				}

				//Do we check IsNullable?
				// TODO: find out why a certain Parameter would not take a null value...
				// From reading the .NET SDK the default is to NOT accept a null value. 
				// I definitely need to look into this more...
				st.Parameters[index].Value = DBNull.Value;
			}
			else
			{
				if (IsDebugEnabled)
				{
					Log.Debug("binding '{0}' to parameter: {1}", ToLoggableString(value, session.Factory), index);
				}

				Set(st, value, index, session);
			}
		}
``` 
to:
```
                public sealed override void NullSafeSet(DbCommand st, object value, int index, ISessionImplementor session)
		{
			if (value == null)
			{
				if (IsDebugEnabled)
				{
					Log.Debug("binding null to parameter: {0}", index);
				}

				//Do we check IsNullable?
				// TODO: find out why a certain Parameter would not take a null value...
				// From reading the .NET SDK the default is to NOT accept a null value. 
				// I definitely need to look into this more...
				st.Parameters[index].Value = DBNull.Value;
			}
			else if (value is DelayedPostInsertIdentifier)
			{
				if (IsDebugEnabled)
				{
					Log.Debug("binding 0 to parameter: {0}", index);
				}

				st.Parameters[index].Value = 0;
			}
			else
			{
				if (IsDebugEnabled)
				{
					Log.Debug("binding '{0}' to parameter: {1}", ToLoggableString(value, session.Factory), index);
				}

				Set(st, value, index, session);
			}
		}
```
I have tested it locally so far. I'm going to make pull request, but so far I have problems with generating an asynchronous test.

**Comment by bahusoid** [comment] 2020-06-09 09:43
I don't get your fix.. How supplying 0 as parameter value would return anything relevant to your query? Do you expect `entity` be present in query results?

**Comment by hazzik** [comment] 2020-06-09 09:52
Dont worry too much about async code. We can do it ourselves.

**Comment by galamai** [comment] 2020-06-09 10:00
I think entities that are not stored in the database should not fall into the query response. Therefore, 0 as an identifier parameter is quite a suitable value.
I create pull request for fix it. https://github.com/nhibernate/nhibernate-core/pull/2416

**Comment by bahusoid** [comment] 2020-06-09 10:21
> I think entities that are not stored in the database should not fall into the query response. 

Query on transient entity is a bit strange use case. I would say it looks more like erroneous usage to me. So exception might be appropriate behavior to warn user about it instead of silent query execution..

Also maybe I forget how it really works but shouldn't `FlushMode.Auto` flush this session before query execution?

**Comment by hazzik** [comment] 2020-06-09 10:41
`FlushMode.Auto` does not work because there is no transaction. 

The correct behavior would be to throw TransientEntityException.

**Comment by galamai** [comment] 2020-06-09 11:41
I think this is normal behavior. If we change the request a little, it will also not return anything and this is expected. In this case, there will be no errors, since the key is passed to the condition right away, and not calculated using the session.
```
var entities= session.Query<Entity>().Where(x => x == entity).ToList();
```

**Comment by galamai** [comment] 2020-06-12 11:19
@bahusoid, @hazzik any news?

**Comment by bahusoid** [comment] 2020-06-12 11:30
As mentioned by hazzik:
> the fix would not work with identifiers of other types.

And I don't think it's correct for int type too. 0 might be correct db value. Value should be retrieved from `enitty.Id`.

But to me exception for transient entity looks as OK behavior that doesn't need fixing.

**Comment by galamai** [comment] 2020-06-15 12:22
I compared this behavior with entity framework core 3 comparison by reference for an entity that is not yet stored in the table returns exactly parameter 0. DelayedPostInsertIdentifier exists only for auto-increment fields, so I believe that the value 0 in this case is correct.

**Comment by hazzik** [comment] 2022-08-30 00:13
Duplicate of #3041

**Closed by hazzik** 2022-08-30 00:13 UTC
