### ISSUE TITLE
NHibernate 5.5.2 Nuget pacakge throws Binary formatter error while used in .net 8 

### ISSUE THREAD

**Issue by Additive-abc** [nhibernate/nhibernate-core#3585] opened 2024-07-12 05:55 UTC
Hello,

NHibernate 5.5.2 Nuget pacakge throws Binary formatter error while used in .net 8  please provide 5.6 version

**Comment by hazzik** [comment] 2024-07-12 06:18
Duplicate of #2603

from @fredericDelaporte:
> TLDR: review how your application works and eliminate any use of the binary serializer it does. NHibernate does not use it by itself, but only through the application choices, like mappings using SerializableType, uses of second level cache providers relying on binary serialization, ....

**Comment by hazzik** [comment] 2024-07-12 06:19
Duplicate of #2603

from @fredericDelaporte:
> TLDR: review how your application works and eliminate any use of the binary serializer it does. NHibernate does not use it by itself, but only through the application choices, like mappings using SerializableType, uses of second level cache providers relying on binary serialization, ....

**Comment by hazzik** [comment] 2024-07-12 06:20
Duplicate of #2603

**Closed by hazzik** 2024-07-12 06:20 UTC
