### ISSUE TITLE
Linq Group by Count produce wrong SQL

### ISSUE THREAD

**Issue by gokhanabatay** [nhibernate/nhibernate-core#2240] opened 2019-10-06 21:34 UTC
Linq  GroupBy Expression Count produce wrong sql.
I think grouped expression "Count" method needs to implemented as subquery  #2210
Tested with NHibernate master code.

```c#
var count = ISession.Query<CrdCardAccount>()
               .GroupBy(x => x.LastStmtDate)
               .Count();
```

Wrong SQL:
```sql
  SELECT CAST (COUNT (*) AS NUMBER (10, 0)) AS col_0_0_
    FROM SCH.CRD_CARD_ACCOUNT crdcardacc0_
GROUP BY crdcardacc0_.LAST_STMT_DATE
```
Correct SQL:
```sql
Select Count(1) FROM(
  SELECT crdcardacc0_.LAST_STMT_DATE AS col_0_0_
    FROM SCH.CRD_CARD_ACCOUNT crdcardacc0_
GROUP BY crdcardacc0_.LAST_STMT_DATE)
```

Workaround if we select Max then Count results is true but Sql is odd. 
We need a paging extension method, this method takes IQueryable<T> first execute Count query then take records with appropriate page size and index. So we cannot use below workaround. 
```c#
var count = ISession.Query<CrdCardAccount>()
              .GroupBy(x => x.LastStmtDate)
              .Select(x => x.Max(grp=>grp.LastStmtDate))
              .Count();
```

Odd SQL with correct result
```sql
  SELECT CAST (COUNT (MAX (crdcardacc0_.LAST_STMT_DATE)) AS NUMBER (10, 0)) AS col_0_0_
    FROM SCH.CRD_CARD_ACCOUNT crdcardacc0_
GROUP BY crdcardacc0_.LAST_STMT_DATE
```

**Comment by bahusoid** [comment] 2019-10-08 12:09
Duplicate of #1123

**Closed by bahusoid** 2019-10-08 12:09 UTC
