### ISSUE TITLE
Wrong WHERE cause generation for one-to-one associations

### ISSUE THREAD

**Issue by OlegUfaev** [nhibernate/nhibernate-core#2169] opened 2019-06-06 12:45 UTC
I'm using Oracle.ManagedDataAccess.Core 2.19.3

I have Device entity that has optional DeviceDiagnostic association.
For clarity I simplified both classes: Device and DeviceDiagnostic.
```
    public class Device
    {
        public virtual int Id { get; set; }

        public virtual string SerialNumber { get; set; }

        public virtual DeviceDiagnostic DeviceDiagnostic { get; set; }
    }

    public class DeviceDiagnostic
    {
        public virtual int DeviceId { get; set; }

        public virtual string StatusDescription { get; set; }
    }

```
By design, Device can have only one DeviceDiagnostic or zero.
So I used one-to-one association.

```
    public class DeviceMap : ClassMap<Device>
    {
        public DeviceMap()
        {
            Id(x => x.Id).GeneratedBy.Assigned();

            Map(x => x.SerialNumber)
                .Not.Nullable()
                .Unique();

            HasOne(x => x.DeviceDiagnostic);
        }
    }

    public class DeviceDiagnosticMap : ClassMap<DeviceDiagnostic>
    {
        public DeviceDiagnosticMap()
        {
            Id(x => x.DeviceId).GeneratedBy.Foreign("Device");

            Map(x => x.StatusDescription)
                .Nullable();
        }
    }
```
When I execute this code
```
        private static void Main(string[] args)
        {
            var sessionFactory = BuildSessionFactorySqlServer();

            using (var session = sessionFactory.OpenSession())
            {
                var devices = session.Query<Device>()
                    .Where(x => x.DeviceDiagnostic == null)
                    .Fetch(x => x.DeviceDiagnostic)
                    .ToArray();
            }
        }

```
I see this SQL query and this is WRONG because it has incorrect where clause. It checks Device.Id which wasn't in where expression at all.
```
    select
        device0_.Id as id1_10_0_,
        devicediag1_.DeviceId as deviceid1_5_1_,
        device0_.SerialNumber as serialnumber2_10_0_,
        devicediag1_.StatusDescription as statusdescription2_5_1_
    from
        Device device0_
    left outer join
        DeviceDiagnostic devicediag1_
            on device0_.Id=devicediag1_.DeviceId
    where
        device0_.Id is null
```
I beleive SQL query should be build something like this, with where cause with check on the second table
```
    select
        device0_.Id as id1_10_0_,
        devicediag1_.DeviceId as deviceid1_5_1_,
        device0_.SerialNumber as serialnumber2_10_0_,
        devicediag1_.StatusDescription as statusdescription2_5_1_
    from
        Device device0_
    left outer join
        DeviceDiagnostic devicediag1_
            on device0_.Id=devicediag1_.DeviceId
    where
        devicediag1_.Id is null
```

I have workaround for this problem
```
        private static void Main(string[] args)
        {
            var sessionFactory = BuildSessionFactorySqlServer();

            using (var session = sessionFactory.OpenSession())
            {
                var devices = session.Query<Device>()
                    .Where(x => !session.Query<DeviceDiagnostic>().Any(dd => dd.DeviceId == x.Id))
                    .Fetch(x => x.DeviceDiagnostic)
                    .ToArray();
            }
        }
```

But I believe "_Where(x => x.DeviceDiagnostic == null)_" should work well, because that's what you expect.

**Comment by bahusoid** [comment] 2019-06-06 12:56
Duplicate of #1274

**Closed** 2019-06-06 14:38 UTC
Labels: r: Duplicate
