### ISSUE TITLE
DB is queried for the version although the entity is not versioned

### ISSUE THREAD

**Issue by CSharpBender** [nhibernate/nhibernate-core#1909] opened 2018-11-23 15:29 UTC
https://github.com/nhibernate/nhibernate-core/blob/a56e68382a9f2554d26157730557ead3c4971b69/src/NHibernate/Persister/Entity/AbstractEntityPersister.cs#L1753
Although IsVersioned is false this query gets executed.

I'm trying to implement a SaveOrUpdate method that will insert an entity if the id is not found in the database and it will update it otherwise. If the entity is versioned and the values are different I'm expecting an exception.

Although the code is working fine, I have an extra query (returns the Id) that gets executed for Replicate. 
```
        public async Task SaveOrUpdateAsync(T entity, CancellationToken cancellationToken = default(CancellationToken))
        {
            var metadata = Session.SessionFactory.GetClassMetadata(typeof(T));
            var id = metadata.GetIdentifier(entity);
            if (id != null && id.ToString() != "0")
            {
                var dbEntity = await Session.GetAsync<T>(id, cancellationToken);
                if (dbEntity != null)
                {
                    Session.Replicate(entity, ReplicationMode.Overwrite);
                    await Session.UpdateAsync(entity, cancellationToken);
                    return;
                }
            }
            await Session.SaveAsync(entity, cancellationToken);
        }

```
I'm using Session.Replicate because otherwise I'm getting an exception. Session.Merge would update the values in the cache but the entity would remain transient.
Ignoring the fact the the entity is not versioned, although L1 cache is populated, the Session.Replicate is hitting the DB to read the version. The `Id` from the `entity` parameter could be used to read the version information from L1 cache.
Calling again Session.Replicate with the same parameter will not hit the DB.

**Comment by fredericDelaporte** [comment] 2018-11-23 16:38
Are you asking for optimizing `Replicate` in the case the entity is not versioned? So you would be asking, in that case, for `Replicate` to first check if an entity with the same identifier is already loaded in the session, before hitting the db to check if it exists?

Maybe why not, I have not studied which impacts it may have.

In any case that would be an improvement, not a bug fix like the title seems to imply. Yes the `GetCurrentVersion` method is called by `Replicate` for non-versioned entities, but it is not an error. When an entity is not versioned, this method may still be used for checking the entity existence (it then yields the entity identifier), as `Replicate` is doing.

Moreover, from what you have written, it seems your actual need is to have a `SaveOrUpdate`. But the session already provides such a method, with exactly that name. Granted, its xml documentation is incomplete and maybe even misleading.
But I do not see in which case it would not do already what you need, and better than your current attempt.
Yes, it even handles entities with assigned identifier generator, without the need for an `unsaved-value` setting in mapping. (It is not needed for other id generator in most cases too, because it has a suitable default value for most of them.) In the case of an assigned id, it will check the entity existence among the entities loaded in session, then in the second level-cache, then in the database.

> Session.Merge would update the values in the cache but the entity would remain transient.

Not really. `Session.Merge` persist the entity using a instance copied from the supplied instance, and yield back that instance. So actually the entity is persisted, but the supplied instance remains untouched and detached. Use the instance returned by `Merge` if you need to work afterwards with the entity instance managed by the session. Yes it means that when using `Merge` with a detached instance, your entity will be represented by two instances: the one you have supplied, which remains detached, and the one returned by `Merge`.

**Comment by CSharpBender** [comment] 2018-11-23 20:39
Hi,
Thanks for the quick response.

IMO this is a bug because `Session.Get` uses the L1 cache but `Replicate` hits the DB although it's not using the result.
My code is not so bad, except for the replicate query. I should have just one query for the `Get` if the object is not in the Session.
I'm opened to any suggestions.

I've tried with `SaveOrUpdate` but it was doing update when the Id was populated. There were some articles (might be wrong) that were saying that the version(null) was used to determine if it's an insert or an update. My entity is not versioned.
Also if there was an entity in the Session with the same Id I was getting an error.

The problem with `Session.Merge` is that my method from the repository doesn't have a ref, out or a return value. I can't change the interface.

**Comment by fredericDelaporte** [comment] 2018-11-23 23:07
I do not understand how can it be considered that it does not use the result. The code is [here](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/Event/Default/DefaultReplicateEventListener.cs#L58), and definitely it uses the retrieved value to determine what it should do. This works as expected.

Comparing `Get` and `Replicate` sounds a bit pointless, they do not have a similar semantic at all.

> I've tried with `SaveOrUpdate` but it was doing update when the Id was populated.

Maybe should this be investigated, instead of calling a bug the behavior of a method used as a workaround. But of course if the `id` generator is not the `assigned` one, or if an `unsaved-value` has been set for the id to anything else than `undefined`, this is a normal behavior of `SaveOrUpdate`.

**Comment by CSharpBender** [comment] 2018-11-24 00:31
I mentioned  a few times that my entity is not versioned. 
If it were, that code might make sense: `object realOldVersion = persister.IsVersioned ? oldVersion : null;`

**Comment by fredericDelaporte** [comment] 2018-11-24 11:42
> I mentioned a few times that my entity is not versioned.

And I have replied in my very first comment here:

>Yes the `GetCurrentVersion` method is called by `Replicate` for non-versioned entities, but it is not an error. When an entity is not versioned, this method may still be used for checking the entity existence (it then yields the entity identifier), as `Replicate` is doing.

Arguing on this is going nowhere.

> I can't use SaveOrUpdate because I might have an object with the same Id in the session

Then as explained in the article you have linked, that is `Merge` that should be used. You have explained you cannot use it because your application API shape does not allow it. Well, that is somewhat your application trouble.

> Is there a way to determine that there is an object with the same Id in the session? I could call Session.Evict on it.

The less hacky way is likely to choose to always have it first in the session by `Load`ing it (provided it is lazy, it will not hit the db but yield an uninitialized proxy if it was not already in the session) then `Evict`ing it.

Otherwise the "internal" session interface can be reached with `GetSessionImplementation()`, then access its `PersistenceContext`, and use `ContainsEntity`. It will require to have also resolved the persister for the entity, which can be done from `ISessionImplementor.Factory.TryGetEntityPersister`.

But anyway if you have cascade enabled and do `SaveOrUpdate` graphs, such operations would have to be done for each entity in the graph. This will be quickly quite unpractical.

> At some point there was a method `SaveOrUpdateCopy` that seemed to do what I need.

No, it was just `Merge` with another name, implemented before the current `Merge` was ported from NHibernate. It was working the same way than `Merge`, leaving the supplied instance untouched and detached from the session, and returning the one attached in the session. See [NH-2508](https://nhibernate.jira.com/browse/NH-2508).

All this said,
Most of this discussion, for the purpose of this issue tracker, is off-topic.

Support and usage questions are to be directed to the user groups:
http://nhibernate.info/groups.html

At the point where this issue is now, better close it, and re-open a new one if you wish to ask for

> optimizing `Replicate` in the case the entity is not versioned. So you would be asking, in that case, for `Replicate` to first check if an entity with the same identifier is already loaded in the session, before hitting the db to check if it exists.

**Closed by fredericDelaporte** 2018-11-24 11:42 UTC

**Comment by CSharpBender** [comment] 2018-11-26 13:02
Thanks Frederic for the help.

Using your input I've managed to create the method that I needed:
- check if there is an entity with the same id register in the session (else call SaveOrUpdate)
- merge `var mergedEntity = await Session.MergeAsync(entity, cancellationToken)`
- using reflection copy all the properties from the `mergedEntity` object into my parameter
- call Session.Evict on the "mergedEntity" instance
- call Save/Update on my entity
