### ISSUE TITLE
SetSnapShot<T> internal :: update breaking legacy software

### ISSUE THREAD

**Issue by figueiredorj** [nhibernate/nhibernate-core#2829] opened 2021-06-16 14:28 UTC
Hi all,
Me and my team were asked to update a legacy software done with nhibernate as data access.

There is a broken feature we found related to update of internal class **SetSnapShot<T>**
As I don't fully remember everything from nhibernate as my previous usage was around 2009 there is a behavior that first I though odd.. but well it was working.

on save of a self entity (save as -> self) it duplicated entry of children parent.
previously, as it was a list, there was no issue with it; updating internal class to be supported by a dictionary means that you cannot add a duplicated entry.

my question is: should this be handled by nhibernate?

- on Add method of internal class:
`		public void Add(T item)
		{
			if (item == null)
			{
				_hasNull = true;
				return;
			}
// add validation if values does not contains item
			_values.Add(item, item);
		}
`
- add a distinct on GetSnapshot
`
		public override object GetSnapshot(ICollectionPersister persister)
		{
			var clonedSet = new SetSnapShot<T>(WrappedSet.Count);
// select with a "distinct"
			var enumerable = from object current in WrappedSet
							 select persister.ElementType.DeepCopy(current, persister.Factory);
			foreach (var copied in enumerable)
			{
				clonedSet.Add((T)copied);
			}
			return clonedSet;
		}
`

- else it should be handled on application...

Eventually @alexDevBR or @marcelltoth may help me out with this as you were on this development task, and would know better what was expected.

Thanks all

**Comment by bahusoid** [comment] 2021-06-16 14:46
Duplicate of #2802

**Closed by bahusoid** 2021-06-16 14:46 UTC
