### ISSUE TITLE
version 5.3 failed to cast enum as nvarchar

### ISSUE THREAD

**Issue by Nazgaul** [nhibernate/nhibernate-core#2446] opened 2020-07-22 13:01 UTC
All my enum are mapped as nvarchar and the string value is persist to the database.

All my linq queries now is failing
Conversion failed when converting the nvarchar value 'Flagged' to data type int.

The enum values are
 public enum ItemState
    {
        Ok,
        Deleted,
        Pending,
        Flagged
    }
I revert back to 5.2.7 - and hopefully a fix will be soon.

Thanks

The full exception is:

NHibernate.Exceptions.GenericADOException : Failed to execute query batch[SQL: select document0_.Id as col_0_0_, document0_.Name as col_1_0_, document0_.CourseName as col_2_0_, cast(document0_.DocumentType as nvarchar(50)) as col_3_0_, document0_.VoteCount as col_4_0_, document0_.Price as col_5_0_, document0_.CreationTime as col_6_0_, document0_.Views as col_7_0_, document0_.Downloads as col_8_0_, document0_.Purchased as col_9_0_ from sb.[Document] document0_ where document0_.UserId=? and document0_.[State]=?]
---- System.Data.SqlClient.SqlException : Conversion failed when converting the nvarchar value 'Flagged' to data type int.
   at NHibernate.Multi.QueryBatch.ExecuteBatchedAsync(CancellationToken cancellationToken)
   at NHibernate.Multi.QueryBatch.ExecuteAsync(CancellationToken cancellationToken)
   at NHibernate.Multi.QueryBatchExtensions.FutureList`1.GetValueAsync(CancellationToken cancellationToken)
   at NHibernate.Multi.QueryBatchExtensions.FutureEnumerable`1.GetEnumerableAsync(CancellationToken cancellationToken)
   at

**Comment by fairking** [comment] 2020-07-22 15:20
Agree. I have the same issues.
```
        public static IType GetNHibernateType(System.Type propType, PropertyInfo prop)
        {
            if (propType.IsEnum)
                return (IType)Activator.CreateInstance(typeof(EnumStringType<>).MakeGenericType(propType));
            ....
```
The actual error:
```
ERROR|NHibernate.Util.ADOExceptionReporter|Conversion failed when converting the varchar value 'Completed' to data type int.
---> System.Data.SqlClient.SqlException (0x80131904): Conversion failed when converting the varchar value 'Completed' to data type int.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.<>c__DisplayClass186_0.<ReadAsync>b__1(Task t)
   at System.Data.SqlClient.SqlDataReader.InvokeRetryable[T](Func`2 moreFunc, TaskCompletionSource`1 source, IDisposable objectToDispose)
--- End of stack trace from previous location where exception was thrown ---
   at NHibernate.Driver.NHybridDataReader.ReadAsync(CancellationToken cancellationToken)
   at NHibernate.Loader.Loader.DoQueryAsync(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder, CancellationToken cancellationToken)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollectionsAsync(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder, CancellationToken cancellationToken)
   at NHibernate.Loader.Loader.DoListAsync(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder, CancellationToken cancellationToken)
ClientConnectionId:8629a5df-c493-4ce4-b62f-578ac859e9fa
Error Number:245,State:1,Class:16
   --- End of inner exception stack trace ---
   at NHibernate.Loader.Loader.DoListAsync(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer, QueryCacheResultBuilder queryCacheResultBuilder, CancellationToken cancellationToken)
   at NHibernate.Loader.Loader.ListIgnoreQueryCacheAsync(ISessionImplementor session, QueryParameters queryParameters, CancellationToken cancellationToken)
   at NHibernate.Hql.Ast.ANTLR.QueryTranslatorImpl.ListAsync(ISessionImplementor session, QueryParameters queryParameters, CancellationToken cancellationToken)
   at NHibernate.Engine.Query.HQLQueryPlan.PerformListAsync(QueryParameters queryParameters, ISessionImplementor session, IList results, CancellationToken cancellationToken)
   at NHibernate.Impl.SessionImpl.ListAsync(IQueryExpression queryExpression, QueryParameters queryParameters, IList results, Object filterConnection, CancellationToken cancellationToken)
   at NHibernate.Impl.SessionImpl.ListAsync(IQueryExpression queryExpression, QueryParameters queryParameters, IList results, Object filterConnection, CancellationToken cancellationToken)
   at NHibernate.Impl.AbstractSessionImpl.ListAsync(IQueryExpression queryExpression, QueryParameters parameters, CancellationToken cancellationToken)
   at NHibernate.Impl.AbstractQueryImpl2.ListAsync(CancellationToken cancellationToken)
   at NHibernate.Linq.DefaultQueryProvider.ExecuteQueryAsync(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery, CancellationToken cancellationToken)
   at NHibernate.Linq.DefaultQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
```

**Comment by maca88** [comment] 2020-07-22 17:23
@Nazgaul can you share how your linq query looks like and what enum type (e.g. EnumStringType) are you using for mapping the `State` property?
From the exception it seems like to be: `session.Query<Document>().Where(o => o.UserId == userId && o.State == ItemState.Flagged).ToFuture().ToList()`, but I couldn't reproduce the issue with such query.

@fairking your issue is already fixed by #2443.

**Comment by Nazgaul** [comment] 2020-07-22 17:55
@maca88 

this is my linq query
   var documentCoursesFuture = _session.Query<Document>()
                    .Fetch(f => f.User)
                    .Where(w => w.User.Id == query.Id && w.Status.State == ItemState.Ok)
                    .Select(s => s.Course.Id).Distinct()
                    .ToFuture();

   NHibernate.Exceptions.GenericADOException : Failed to execute query batch[SQL: select distinct document0_.CourseName as col_0_0_ from sb.[Document] document0_ where document0_.UserId=? and document0_.[State]=?]
    ---- System.Data.SqlClient.SqlException : Conversion failed when converting the nvarchar value 'Flagged' to data type int.

the mapping is
 Map(x => x.State)
                .CustomType<GenericEnumStringType<ItemState>>().Not.Nullable();

the EnumStringType inherit from EnumStringType support ignore case

 public override object? GetInstance(object code)
        {
            if (!(code is string p))
            {
                return null;
            }
            return Enum.Parse(typeof(TEnum), p, true);
        }

**Comment by Nazgaul** [comment] 2020-07-22 17:59
@maca88 
the fetch is causing this issue. remove the line Fetch(f => f.User) will make my unit test to pass.

**Comment by maca88** [comment] 2020-07-22 18:36
@Nazgaul thanks for the info, closing the issue as it was already reported in #2439 and fixed.

**Closed by maca88** 2020-07-22 18:36 UTC

**Comment by fairking** [comment] 2020-07-22 18:48
Thank you guys. Tested the branch `origin/5.3.x` enums an everything else is working with no issues so far now.
