### ISSUE TITLE
"System.InvalidCastException : Unable to cast object of type (MyClass) to type 'System.Object[]'."   

### ISSUE THREAD

**Issue by mubeda** [nhibernate/nhibernate-core#2451] opened 2020-07-24 19:26 UTC
We are working on a project that support almost all dbms.  We have unit test that runs in all off them,  we are experience mayor test fails fsince 5.3 upgrade (no problems with 5.2.7).  Mssql, Mariadb, Postgresql (i did not try Mysql, Oracle yet).  The only one not affected are test cases based on FirebirdEmbedded.

We use FluentNhibernate, UnitOfWork and Repository patterns.

Callstack:
```
  Message: 
    NHibernate.Exceptions.GenericADOException : Failed to execute query batch[SQL: SELECT this_.intId_pk as intid1_27_4_, ...  (big select join here);
    ]
    ---- System.InvalidCastException : Unable to cast object of type 'MyClass' to type 'System.Object[]'.
  Stack Trace: 
    QueryBatch.ExecuteBatched()
    QueryBatch.Execute()
    FutureList`1.get_Value()
    FutureValue`1.get_Value()
    GenericReadOnlyRepository`1.GetPagedList(IQueryOver`2 query, DatabaseQueryParams queryParams) line 203
```
GenericReadOnlyRepository code:
```
        public override IPagedList<TEntity> GetPagedList(IQueryOver<TEntity, TEntity> query, DatabaseQueryParams queryParams)
        {
            if (queryParams == null)
            {
                queryParams = new DatabaseQueryParams();
            }

            var result = new PagedList<TEntity>
            {
                Page = queryParams.Page,
                PageSize = queryParams.PageSize,
            };

            if (query == null)
            {
                return result;
            }

            if (queryParams.IsPaginationEnabled)
            {
                query.Skip((queryParams.Page - 1) * queryParams.PageSize).Take(queryParams.PageSize);
            }

            PrepareCriteria(query.UnderlyingCriteria, queryParams);

            // this is important to avoid duplicated records
            query.TransformUsing(Transformers.DistinctRootEntity);

            var countCriteria = CriteriaTransformer.TransformToRowCount(query.UnderlyingCriteria);
            countCriteria.SetProjection(Projections.RowCount());

            var entities = query.Future<TEntity>();
            var totalCount = countCriteria.FutureValue<int>();

            result.TotalCount = totalCount.Value; // both will be executed here
            foreach (TEntity obj in entities.GetEnumerable())
            {
                result.Items.Add(obj);
            }

            return result;
        }
```
the spot where the exception is throw is this one "      result.TotalCount = totalCount.Value; // both will be executed here"
Let me know if you need more info from my side.

**Comment by bahusoid** [comment] 2020-07-24 20:14
Duplicate of #2440

**Closed by bahusoid** 2020-07-24 20:14 UTC
