### ISSUE TITLE
Nhibernate 5.1 not support mysql when query by sum

### ISSUE THREAD

**Issue by tjliuqian** [nhibernate/nhibernate-core#1934] opened 2018-12-10 13:16 UTC
when the database table is empty,the system run these by linq:
roomRepo.Query<RoomEntity>().Where(p=>p.State==2).Sum(p=>p.Amount);
then throw exception 
可为空的对象必须具有一个值。   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 lambda_method(Closure , IEnumerable`1 )
   在 NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)

**Comment by fredericDelaporte** [comment] 2018-12-10 13:49
I speculate this is a duplicate of #1134, which is not an issue. (Better try to translate the exception message, it would reduce the guessing part.)

Cast your `p.Amount` to a nullable type in order for the expression to be able to support empty data sets.

**Closed by fredericDelaporte** 2018-12-10 13:49 UTC
