### ISSUE TITLE
Incorrect SQL for cast inside a linq join (MS SQL)

### ISSUE THREAD

**Issue by micmerchant** [nhibernate/nhibernate-core#2040] opened 2019-03-05 15:51 UTC
Hello,

we are currently updating from an old NHibernate 4 version to the current NHibernate 5 (5.2.3) version and are facing some issues. 

One of our models contains a nullable string column which is joined on a column with a different type of an other table by using ToString() within the join, e.g:

```javascript
q =
from o in db.Orders
join s in db.Shippers
	on o.ShippedTo equals s.Reference.ToString()
where o.ShippedTo != null
select o.OrderId;
```
This worked in NHibernate 4 but fails in NHibernate 5. Here is a logged query example from our production code with 
[Join-Exception.txt](https://github.com/nhibernate/nhibernate-core/files/2931670/Join-Exception.txt)
NHibernate 4 and NHibernate 5.

```sql
-- NHibernate 4

select invruletem0_.ID as col_0_0_
from   InvRuleTemplate invruletem0_,
       InvRule invrule1_
where  (invruletem0_.Mandator & -1 /* @p0 */) != 0
       and (invrule1_.Mandator & -1 /* @p0 */) != 0
       and invrule1_.TargetID = cast(invruletem0_.ID as nvarchar(50))
       and (invrule1_.TargetID is not null)

-- NHibernate 5

select invruletem0_.ID as col_0_0_
from   InvRuleTemplate invruletem0_,
       InvRule invrule1_
where  (invruletem0_.Mandator & -1 /* @p0 */) != 0
       and (invrule1_.Mandator & -1 /* @p0 */) != 0
       and invrule1_.TargetID = invruletem0_.ID
       and (invrule1_.TargetID is not null)
```
It looks like that the .ToString() cast isn't translated into SQL anymore. This only happens when the string column is nullable. I guess the query translator recognizes that a cast isn't necessary for not nullable string columns.

This problem is reproducable with a unit test with the northwind domainmodel:
```javascript
[TestFixture]
public class LinqQuerySamples : LinqTestCase
{
	...

	[Category("JOIN")]
	[Test(Description = "This sample shows how to construct a join where one side is a nullable string and the other side a not nullable guid.")]
	public void DLinqJoin11()
	{
		var q =
			from o in db.Orders
			join s in db.Shippers
				on o.ShippedTo equals s.Reference.ToString()
			where o.ShippedTo != null
			select o.OrderId;

		ObjectDumper.Write(q);
	}
	
	....
}
```

I've also attached the unit test exception.

Thx in advance. Best regards!
[Join-Exception.txt](https://github.com/nhibernate/nhibernate-core/files/2931675/Join-Exception.txt)

**Comment by fredericDelaporte** [comment] 2019-03-05 20:18
May be related to #2029 (or maybe have the same root cause), and could be fixed by #2036 (which does also some changes on a path not specific to `sum`). @maca88, may you check that?

@micmerchant, if you can tell from which minor version the trouble has appeared (only 5.2, or 5.1 too, or 5.0 too, or 4.1 too if you were using 4.0), we would appreciate it.

**Comment by maca88** [comment] 2019-03-05 20:52
I've checked the issue and #2036 does not solve the problem. The issue was introduced with #1856 by adding the following lines:
https://github.com/nhibernate/nhibernate-core/blob/39bf75393e0b8a5856ee4ca317353521474583d2/src/NHibernate/Linq/Functions/StringGenerator.cs#L329-L332

I will analyze the mentioned PR and try to find a general solution.

**Comment by micmerchant** [comment] 2019-03-06 11:50
You are right. This only happens in context of Guids. 

@fredericDelaporte We are updating from NHibernate 4.0.3.

**Comment by micmerchant** [comment] 2019-03-06 11:56
What about simply adding a custom function to the MsSql2000Dialect.cs class? e.g.

```javascript
public class MsSql2000Dialect : Dialect
{
	...
	protected virtual void RegisterFunctions()
	{
		...
		// after
		RegisterFunction("str", new SQLFunctionTemplate(NHibernateUtil.String, "cast(?1 as nvarchar(50))"));
		// new one
		RegisterFunction("strguid", new SQLFunctionTemplate(NHibernateUtil.String, "cast(?1 as nvarchar(50))"));
		...
	}
	...
}
```

**Comment by lillo42** [comment] 2019-03-06 13:11
@micmerchant Just to know, Which version of MS SQL are you using?

@maca88 Probably is missing the code this code, on class ``` MsSql2000Dialect```:

```
RegisterFunction("strguid", new SQLFunctionTemplate(NHibernateUtil.String, "cast(?1 as nvarchar(50))"));
```
Like @micmerchant mention,

It`s stranger because I test on MS Server 2017 and works, I will test again but with that test case

**Comment by micmerchant** [comment] 2019-03-06 13:28
We support MsSql Server 2012 upwards.

**Comment by maca88** [comment] 2019-03-06 16:58
Indeed, registering `strguid` function for `MsSql2000Dialect` is the correct solution. #1856 didn't register a custom function for it because the added test which uses a string parameter does not need it as Sql Server implicitly converts the parameter to a `uniqueidentifier`. #2042 adds the missing registration and an additional test for it.

**Comment by fredericDelaporte** [comment] 2019-03-06 22:01
Regression in 5.2.0, as checked by @maca88 in #2042. You may use 5.1.x instead till 5.2.5 is released, if this regression is a blocker for you.

**Comment by micmerchant** [comment] 2019-03-07 07:48
Well, we are using a custom NHibernate build anyways, which means that I can apply this fix directly in our code base. So I'm fine with adding it in the 5.2.5 release.

**Comment by micmerchant** [comment] 2019-03-07 13:21
@maca88 
I must honestly say that i was confused about your added unit test

```javascript
[Test]
public void CompareStringColumnWithGuidToString()
{
	using (var session = OpenSession())
	{
		var list = session.Query<Entity>()
						  .Where(x => x.Id.ToString() == x.Name)
						  .ToList();

		Assert.That(list, Has.Count.EqualTo(0));
	}
}
```

and the simplicity of reproduction of the bug. I thought this was all about using guids and strings in a join context. But i was misleaded by my own unit tests. I had a similar one, which didn't fail. 

```javascript
[Test(Description = "This test checks a string cast of a not nullable guid column in the where condition.")]
public void NotNullableGuidToStringWithEqualsOperatorComparisonInWhereConditionMethodSyntaxTest1()
{
	INHibernateSession session = NHibernateSessionManager.Instance.GetSession();

	string vehicleId = VehicleInitializer.SomeVehicleId.ToString();

	var result = session.Query<IVehicle>()
						.Where(v => v.ID.ToString() == vehicleId)
						.ToList();
}
```

It didn't fail because the sequal server of course supports this kind of comparison, because the other side is a Guid already. By changing vehicleId to a string e.g. "Test", it would fail. 

So the query of the unit test above, gets translated into this:

```sql
select vehicle0_.ID                     as id1_631_,
       ....
from   Vehicle vehicle0_
where  (vehicle0_.[Mandator] & -1 /* @p0 */) != 0
       and cast(vehicle0_.ID as nvarchar(50)) = 'eca27f3a-42bb-4b72-a481-ad8f8a40ce69' /* @p1 - cle0_.ID as nvarchar(50)) */
```

And here I'm asking myself now, if it wouldn't be an improvement if the query translator would check the type of both sides of the comparison and then decides if a string cast is necessary at all. E.g. if the constant is already a valid Guid then a cast wouldn't be necessary.

What do you think?

**Comment by maca88** [comment] 2019-03-07 17:34
> wouldn't be an improvement if the query translator would check the type of both sides of the comparison and then decides if a string cast is necessary at all

Yes it would be an improvement, maybe by introducing a special logic that would avoid common "mistakes" made by the user like the example that you provided, which in this case would produce the same sql as the following query:
```
var vehicleId = VehicleInitializer.SomeVehicleId;
var result = session.Query<IVehicle>()
                    .Where(v => v.ID == vehicleId)
                    .ToList();
```
of course the logic would need to be dialect specific.

**Comment by micmerchant** [comment] 2019-03-08 07:01
From that point of view, you are absolutly right :) It would only hide a mistake in the written query code, which you would never see then e.g. via the NHibernateProfiler. And i can't come up with a better example.

Thx a lot.

**Closed** 2019-03-09 23:43 UTC
Labels: Regression, c: DataProviders / Dialects, p: Minor, r: Fixed, t: Bug
