### ISSUE TITLE
Linq query uses implicit join incorrectly

### ISSUE THREAD

**Issue by jehhynes** [nhibernate/nhibernate-core#2881] opened 2021-08-03 15:20 UTC
Take the following one-to-many scenario:

```
public class Job
{
     public long Id { get; set; }
     public Error Error { get; set; } //Nullable many-to-one
}

public class Error
{
     public long Id { get; set; }
}
```

And the following Linq query:

`Session.Query<Job>().Where(j => j.Error == null).ToList();`

In NHibernate version 5.2.7 the generated SQL looks like the following (simplified to just show the join mechanism (or lack of) and where clause)

`from Job job_ where job_.ErrorId is null`

Beginning in NHibernate version 5.3.0 the generated SQL now uses an implicit cross-join instead:

`from Job job_, Error error_ where job_.ErrorId=error_.Id and error_.Id is null`

The issue here is that this will always return zero rows because "job_.ErrorId=error_.Id" and "error_.Id is null" can never both be true.

I've tested this using various NHibernate versions and isolated 5.3.0 as the first version this bug occurs in.

**Comment by bahusoid** [comment] 2021-08-03 21:23
`where job_.ErrorId is null` is not correct SQL either for `not-found="ignore"` mapping. Left join is required in this case.

Duplicate of #2611

**Closed by bahusoid** 2021-08-03 21:23 UTC
