### ISSUE TITLE
session.Replicate() doesn't perform idendity insert

### ISSUE THREAD

**Issue by AxxlForce** [nhibernate/nhibernate-core#2261] opened 2019-10-28 10:44 UTC
When I'm using session.Replicate it does not insert the identifier of the entities but instead generates new ones which is in contradiction to the documentation and breaks my application. The DB I want to replicate to is Postgres.

NHibernate Version is 4.0.0.4000

**Comment by fredericDelaporte** [comment] 2019-10-29 20:20
The `identity` case is not supported, and the xml documentation should be updated to reflect this.

Inserting into an `identity` column is a maintenance task that most ORMs will likely never carry out.

**Comment by hazzik** [comment] 2019-10-30 23:17
https://hibernate.atlassian.net/browse/HHH-2716

**Comment by hazzik** [comment] 2019-10-31 21:00
Duplicate of #861

**Closed by hazzik** 2019-10-31 21:00 UTC
Labels: c: Documentation, p: Minor, t: Improvement
