### ISSUE TITLE
LINQ DML insert resolves incorrect query source

### ISSUE THREAD

**Issue by gliljas** [nhibernate/nhibernate-core#2899] opened 2021-08-25 14:35 UTC
```
contacts
   .Where(c=>session.Query<Receipts>().Any(r=>r.RecieptType='Purchase' && r.ContactId==c.ContactId))
   .Select(c=>c.Id)
   .InsertInto(c=>new LogRow{ContactId=c.Id})
```

The query source c in the "Any" subquery is resolved to "Contact", i.e the name of the table, but it should be the prefix.

Will create reproducing unit test.

**Comment by bahusoid** [comment] 2021-08-25 14:56
Looks like duplicate of https://github.com/nhibernate/nhibernate-core/issues/2594

**Comment by gliljas** [comment] 2021-08-25 15:04
Indeed it does.

**Comment by bahusoid** [comment] 2021-08-31 07:50
Duplicate of #2594

**Closed by bahusoid** 2021-08-31 07:50 UTC
