### ISSUE TITLE
Min on composite user type property throws "must be reducible node" exception

### ISSUE THREAD

**Issue by martin-the-geek** [nhibernate/nhibernate-core#2883] opened 2021-08-04 00:06 UTC
Using the following setup

```
public class Foo
{
    public virtual int Id { get; set; }
    public virtual Bar PropBar { get; set; }
}

public class Bar
{
    public virtual int Value { get; set; }
}
```

Composite user type
```
public class BarType : ICompositeUserType
{
    public new bool Equals(object x, object y)
    {
        if (ReferenceEquals(x, y))
        {
            return true;
        }

        if (x == null || y == null)
        {
            return false;
        }

        return x.Equals(y);
    }

    public string[] PropertyNames => new[] { "Value" };

    public IType[] PropertyTypes => new IType[] { NHibernateUtil.Int32 };

    public object GetPropertyValue(object component, int property)
    {
        var p = (Bar) component;
        return p.Value;
    }

    public void SetPropertyValue(object component, int property, object value)
    {
        throw new NotImplementedException();
    }

    public System.Type ReturnedClass => typeof(Bar);

    public int GetHashCode(object x) => x.GetHashCode();

    public object NullSafeGet(DbDataReader dr, string[] names, ISessionImplementor session, object owner)
    {
        var value = (Int32?) NHibernateUtil.Int32.NullSafeGet(dr, new[] { names[0] }, session, owner);
        return value == null ? null : new Bar { Value = value.Value };
    }

    public void NullSafeSet(DbCommand cmd, object value, int index, bool[] settable, ISessionImplementor session)
    {
        NHibernateUtil.Int32.NullSafeSet(cmd, ((Bar) value)?.Value, index, session);
    }

    public object DeepCopy(object value) => value;

    public bool IsMutable => true;

    public object Disassemble(object value, ISessionImplementor session) => DeepCopy(value);

    public object Assemble(object cached, ISessionImplementor session, object owner) => DeepCopy(cached);

    public object Replace(object original, object target, ISessionImplementor session, object owner) => original;
}
```

Mapping
```
<class name="Foo" table="Foo">
  <id name="Id" unsaved-value="0">
    <generator class="assigned"/>
  </id>

  <property name="PropBar" type="BarType">
    <column name="PropBarValue"/>
  </property>
</class>
```

The following would work in 5.2.7 but throws in 5.3.0
```
session.Query<Foo>().Select(f => f.PropBar.Value).Min();
```

**Comment by bahusoid** [comment] 2021-08-04 07:45
Duplicate of #2856

**Closed by bahusoid** 2021-08-04 07:45 UTC
