### ISSUE TITLE
MappingByCode discriminator column with string type throws exception

### ISSUE THREAD

**Issue by SamerX** [nhibernate/nhibernate-core#2717] opened 2021-03-30 09:15 UTC
I am using `ConventionModelMapper` to map my entities, I am using a table per hierarchy strategy to map two entities with a shared parent. When I try to map the discriminator column to type string, it fails:

```C#
mapper.Class<NotificationChannel>(
    m =>
    {
        m.Table("notificationchannels");
        m.Discriminator(
            x =>
            {
                x.Column("discriminator");
                x.Type(NHibernateUtil.String);
            });
    });
```

Error: No parameterless constructor defined for type 'NHibernate.Type.StringType'.

I tried a lot of ways to make this work but nothing worked. The only way out for me is to map it as a numeric value as it seems the default is a numeric type.

**Comment by bahusoid** [comment] 2021-03-30 09:41
It's a bug.  A simple workaround - cast it to `IType`:
```C#
x.Type((IType)NHibernateUtil.String)
```

**Comment by bahusoid** [comment] 2021-06-04 13:19
So it looks like duplicate of https://github.com/nhibernate/nhibernate-core/issues/1337. But with clear issue description.

**Closed** 2022-08-26 01:11 UTC
