### ISSUE TITLE
Nhibernate and multi tenants with a database for each tenant

### ISSUE THREAD

**Issue by robertorp** [nhibernate/nhibernate-core#1617] opened 2018-03-17 01:05 UTC
Nhibernate and multi tenants with a database for each tenant
Which way to go?

**Comment by fredericDelaporte** [comment] 2018-03-17 08:18
Hibernate has it, so it should be ported from it.

**Comment by fredericDelaporte** [comment] 2018-03-17 08:37
Duplicate of #974.

**Closed by fredericDelaporte** 2018-03-17 08:37 UTC
Labels: c: Core, r: Duplicate, t: New Feature
