### ISSUE TITLE
`System.BadImageFormatException: Bad IL format.` after upgrading to .NET Core 3 and using DefaultProxyFactoryFactory

### ISSUE THREAD

**Issue by nmain** [nhibernate/nhibernate-core#2247] opened 2019-10-14 17:18 UTC
After upgrading to .NET Core 3, I see the error stack reproduced below.  Possibly related to https://github.com/nhibernate/nhibernate-core/issues/2228, but the stated resolution there did not work; the ProxyValidator is on and all properties are virtual.  Let me know if there's anything I can do to help reproduce this.  The failure is in a full application I have that I cannot share the code to, but I may be able to chisel out something sharable.

```
 ---> System.BadImageFormatException: Bad IL format.
   at UserProxy.get_HibernateLazyInitializer()
   at NHibernate.Event.Default.DefaultLoadEventListener.CreateProxyIfNecessary(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options, IPersistenceContext persistenceContext)
   at NHibernate.Event.Default.DefaultLoadEventListener.ProxyOrLoad(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.OnLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.FireLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.InternalLoad(String entityName, Object id, Boolean eager, Boolean isNullable)
   at NHibernate.Type.EntityType.ResolveIdentifier(Object id, ISessionImplementor session)
   at NHibernate.Type.EntityType.ResolveIdentifier(Object value, ISessionImplementor session, Object owner)
   at NHibernate.Engine.TwoPhaseLoad.InitializeEntity(Object entity, Boolean readOnly, ISessionImplementor session, PreLoadEvent preLoadEvent, PostLoadEvent postLoadEvent, Action`2 cacheBatchingHandler)
   at NHibernate.Loader.Loader.InitializeEntitiesAndCollections(IList hydratedObjects, DbDataReader reader, ISessionImplementor session, Boolean readOnly, CacheBatcher cacheBatcher)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies)
   at NHibernate.Loader.Loader.LoadEntity(ISessionImplementor session, Object id, IType identifierType, Object optionalObject, String optionalEntityName, Object optionalIdentifier, IEntityPersister persister)
   --- End of inner exception stack trace ---
   at NHibernate.Loader.Loader.LoadEntity(ISessionImplementor session, Object id, IType identifierType, Object optionalObject, String optionalEntityName, Object optionalIdentifier, IEntityPersister persister)
   at NHibernate.Loader.Entity.AbstractEntityLoader.Load(ISessionImplementor session, Object id, Object optionalObject, Object optionalId)
   at NHibernate.Loader.Entity.AbstractEntityLoader.Load(Object id, Object optionalObject, ISessionImplementor session)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Load(Object id, Object optionalObject, LockMode lockMode, ISessionImplementor session)
   at NHibernate.Event.Default.DefaultLoadEventListener.LoadFromDatasource(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.DoLoad(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.Load(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.ProxyOrLoad(LoadEvent event, IEntityPersister persister, EntityKey keyToLoad, LoadType options)
   at NHibernate.Event.Default.DefaultLoadEventListener.OnLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.FireLoad(LoadEvent event, LoadType loadType)
   at NHibernate.Impl.SessionImpl.Get(String entityName, Object id)
   at NHibernate.Impl.SessionImpl.Get(Type entityClass, Object id)
   at NHibernate.Impl.SessionImpl.Get[T](Object id)
```

**Comment by fredericDelaporte** [comment] 2019-10-14 18:02
So your issue may be related to #2085.
Do you have any interface on your entities ? (See #2085 for the details of why it may cause this.)

**Comment by nmain** [comment] 2019-10-14 18:30
Yes, now that I've had a chance to review #2085 that seems like it would be the cause.

User, my domain type that's dying here, does not implement any interfaces, but it's part of a class hierarchy and some of its subclasses implement interfaces, with the same name on the interface property as the class property.

**Comment by fredericDelaporte** [comment] 2019-10-14 18:44
May you come up with a minimal domain model reproducing the issue? I would expect subclass proxies to fail, not the parent one.
(Even better if you can PR a test case, see [contributing](https://github.com/nhibernate/nhibernate-core/blob/master/CONTRIBUTING.md). Of course since this happens only with .Net Core 3, the PR would have to add a netcoreapp3 target to the test project in order to demonstrate the failure.)

**Comment by nmain** [comment] 2019-10-14 19:12
I'll see what I can do.

**Comment by nmain** [comment] 2019-10-15 17:25
I'm having difficulty isolating something that fails for me.  I even shoved my entire domain model into the NHibernate test suite and it doesn't crash :/

That being said, when I run the NHibernate test suite against `netcoreapp3.0` I see some existing tests failing with `Bad IL format.`  Perhaps that's helpful?

These are all failing:
```
InterceptorDynamicEntity.It
InterceptorDynamicEntity.ItAsync

TuplizerDynamicEntity.It
TuplizerDynamicEntity.ItAsync

InterfaceWithEqualsGethashcodeTests.WhenProxyAnInterfaceShouldInterceptEquals

LazyFieldInterceptorTests.LazyFieldInterceptorIsBinarySerializable

GhostPropertyFixture.AcceptPropertySetWithTransientObject

GhostPropertyFixture.AcceptPropertySetWithTransientObjectAsync
```

**Comment by bahusoid** [comment] 2019-10-16 08:15
@nmain I'm assuming you are on NHIbernate 5.2. Try setting `proxyfactory.factory_class` to `NHibernate.Bytecode.DefaultProxyFactoryFactory`
Does it throw the same error with this legacy proxy factory ?

**Comment by bahusoid** [comment] 2019-10-16 10:33
Actually looking on failing tests it seems we are having problem with legacy proxy factory.

> I'm having difficulty isolating something that fails for me.

That's because default proxy is changed in NHibernate 5.2. You should really try with latest version before reporting. Or at least specify what version are  you using.

**Comment by nmain** [comment] 2019-10-16 12:41
My apologies for not giving more thorough and complete information.

I am using NHibernate 5.2.6.  My application was forcing the use of `DefaultProxyFactoryFactory` by configuration.  (I do not know why it was doing this; there's a lot in this application I don't know about).  When I switch it to `StaticProxyFactoryFactory` the issue goes away.  I've updated the ticket title to reflect that this seems to be an issue specifically with the combination of .NET Core 3 and `DefaultProxyFactoryFactory`.

Since it's working for me now, and I had no particular attachment to `DefaultProxyFactoryFactory`, I have no further need of this ticket.  Feel free to close it unless the combination of `DefaultProxyFactoryFactory` and .NET Core 3 is something the NHibernate team wishes to support.

**Comment by bahusoid** [comment] 2019-10-16 12:49
> When I switch it to StaticProxyFactoryFactory the issue goes away.

If you want to stick to default behavior - It's better not to set this setting at all.

Since `DefaultProxyFactoryFactory` is obsolete I guess issue should be closed as obsolete.

**Closed** 2019-10-16 20:02 UTC
Labels: c: ByteCode providers, p: Minor, r: Obsolete, t: Bug

**Comment by fredericDelaporte** [comment] 2019-10-17 19:42
> I do not know why it was doing this; there's a lot in this application I don't know about

On very old versions of NHibernate, it was required to supply an external proxy factory. If your application is that old, maybe in its previous upgrade processes, the external proxy factory was replaced by the internal one, instead of just "unconfiguring" it.

It could be also that some people seem to think it is better to explicitly set all available settings to their default value, maybe believing it would ease upgrade process by avoiding unexpected changes due too default value changes.

But carefully handled pieces of software do not change defaults for light reasons, and that is instead the opposite which usually happens: upgrade processes are easier when the minimal set of settings are defined, because changes to defaults are usually helpful with newer versions.

In such case you may need to review the settings of your project, remove the ones set to their default values, and check if there is any valid reason for the others values. See [here](https://nhibernate.info/doc/nhibernate-reference/session-configuration.html#configuration-hibernatejdbc) and following paragraph.
