### ISSUE TITLE
Parameter combining in multiquery/multicriteria can easily cause key collisions

### ISSUE THREAD

**Issue by gliljas** [nhibernate/nhibernate-core#1427] opened 2017-11-06 00:16 UTC
When the parameters are combined in a multiquery, a simple index is added to the end. This doesn't work well, for example if the first query has eleven parameters and there are ten other queries in the multi.

p11 from query 1 will become p111, but that will collide with p1 from query 11.

**Comment by hazzik** [comment] 2017-11-06 00:17
I think this was logged somewhere

**Comment by hazzik** [comment] 2017-11-06 00:22
Duplicate of #1357

**Closed by hazzik** 2017-11-06 00:22 UTC
