### ISSUE TITLE
IQueryable<T> Left join get NotImplementedException

### ISSUE THREAD

**Issue by ihorboben** [nhibernate/nhibernate-core#2655] opened 2021-01-28 17:30 UTC
Hi, 
I will be grateful for any thoughts on this matter
I am using NHibernate 5.3.5, FluentNHibernate 3.1.0, trying to join 2 tables.

 ```
var tickets= Session.Query<SupportTicket>();
 var values = Session.Query<TicketValueWithName>();
var tsc = from t in tickets
                               join v in values on t.Id equals v.SupportTicketId into gt
                               from v in gt.DefaultIfEmpty()
                               where t.FieldId == 10280
                               orderby t.Value
                               select t;
```

After execution get  NotImplementedException.
tickets and values tables with one-to-many relationships. 

```
 public class SupportTicket : Entity<long>
{
        public string Subject { get; set; }
        public string Body{ get; set; }
}
```

```
public class TicketValueWithName : Entity<long>
    {
        public long FieldId { get; set; }
        public FieldType FieldType { get; set; }
        public long SupportTicketId { get; set; }
        public string Value { get; set; }
    }

public sealed class SupportTicketModelMapping : ClassMap<SupportTicket>
    {
        public SupportTicketModelMapping ()
        {
            Table("SupportTicket");
            ReadOnly();
            Id(x => x.Id).GeneratedBy.Assigned();
            Map(x => x.Subject );
            Map(x => x.Body);
        }
}

public class TicketValueWithNameMapping : ClassMap<TicketValueWithName>
    {
        public TicketValueWithNameMapping()
        {
            Table("TicketValue");
            Id(x => x.Id).GeneratedBy.Assigned();
            Not.LazyLoad();
            ReadOnly();
            Map(x => x.DateLastModified);
            Map(x => x.FieldId);
            Map(x => x.Value).Length(255).Nullable();
            Map(x => x.SupportTicketId);
        }
    }
```

Exception:
```
[NotImplementedException]
NHibernate.Linq.Visitors.QueryModelVisitor.VisitGroupJoinClause(GroupJoinClause groupJoinClause, QueryModel queryModel, Int32 index) +46
   Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel) +288
   Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel) +80
   NHibernate.Linq.Visitors.QueryModelVisitor.Visit() +25
   NHibernate.Linq.Visitors.QueryModelVisitor.GenerateHqlQuery(QueryModel queryModel, VisitorParameters parameters, Boolean root, Nullable`1 rootReturnType) +543
   NHibernate.Linq.NhLinqExpression.Translate(ISessionFactoryImplementor sessionFactory, Boolean filter) +420
   NHibernate.Hql.Ast.ANTLR.ASTQueryTranslatorFactory.CreateQueryTranslators(IQueryExpression queryExpression, String collectionRole, Boolean shallow, IDictionary`2 filters, ISessionFactoryImplementor factory) +68
   NHibernate.Engine.Query.QueryPlanCache.GetHQLQueryPlan(IQueryExpression queryExpression, Boolean shallow, IDictionary`2 enabledFilters) +592
   NHibernate.Impl.AbstractSessionImpl.GetHQLQueryPlan(IQueryExpression queryExpression, Boolean shallow) +119
   NHibernate.Impl.AbstractSessionImpl.CreateQuery(IQueryExpression queryExpression) +75
   NHibernate.Linq.DefaultQueryProvider.PrepareQuery(Expression expression, IQuery& query) +139
   NHibernate.Linq.DefaultQueryProvider.ExecuteList(Expression expression) +41
   NHibernate.Linq.NhQueryable`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() +135
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +430
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +69
```

**Comment by bahusoid** [comment] 2021-01-31 06:46
Does it work without `order by`?

**Comment by ihorboben** [comment] 2021-01-31 14:21
> Does it work without `order by`?

No.
For me work:
```
var tsc = from t in tickets
          from v in values.Where(x => x.FieldId == 10280 && x.SupportTicketId == t.Id).DefaultIfEmpty()
          orderby v.Value
          select t;
```
Like in the tests.
https://github.com/maca88/nhibernate-core/blob/0132e4cf6e6cb06bdcbf4b2fc70439f44a8ff36f/src/NHibernate.Test/Async/Linq/LinqQuerySamples.cs#L774

**Comment by bahusoid** [comment] 2022-09-01 08:58
Duplicate of #2738

**Closed by bahusoid** 2022-09-01 08:58 UTC
Labels: r: Duplicate
