### ISSUE TITLE
ArgumentException on session Flush

### ISSUE THREAD

**Issue by igorvorona** [nhibernate/nhibernate-core#2802] opened 2021-06-01 20:45 UTC
I have upgraded existing NHibernate 4.0.4 to 5.3.8. All seem to be working with minor changes, but lots of tests failing with the following error when session is either manually flushed or auto-flushed when executing HQL scripts:

```
System.ArgumentException : An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at NHibernate.Collection.Generic.PersistentGenericSet`1.GetSnapshot(ICollectionPersister persister)
   at NHibernate.Engine.CollectionEntry.AfterAction(IPersistentCollection collection)
   at NHibernate.Action.CollectionUpdateAction.Execute()
   at NHibernate.Engine.ActionQueue.InnerExecute(IExecutable executable)
   at NHibernate.Engine.ActionQueue.ExecuteActions[T](List`1 list)
   at NHibernate.Engine.ActionQueue.ExecuteActions()
   at NHibernate.Event.Default.AbstractFlushingEventListener.PerformExecutions(IEventSource session)
   at NHibernate.Event.Default.DefaultAutoFlushEventListener.OnAutoFlush(AutoFlushEvent event)
   at NHibernate.Impl.SessionImpl.AutoFlushIfRequired(ISet`1 querySpaces)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results, Object filterConnection)
   at NHibernate.Impl.SessionImpl.List(IQueryExpression queryExpression, QueryParameters queryParameters, IList results)
   at NHibernate.Impl.AbstractSessionImpl.List(IQueryExpression queryExpression, QueryParameters parameters)
   at NHibernate.Impl.AbstractQueryImpl2.List()
```

**Comment by igorvorona** [comment] 2021-06-02 04:56
It also throws sometimes session.Refresh() in EvictCachedCollections.

**Comment by bahusoid** [comment] 2021-06-02 08:11
Looks like regression from https://github.com/nhibernate/nhibernate-core/pull/2394

@maca88 It seems `SetSnapShot.Add` behaves differently for .NET Core and NetFx. .NET Core version allows duplicates and NetFx throws.
It seems NetFx Add method should use `dic[key] = value` instead of `dic.Add`

**Comment by igorvorona** [comment] 2021-06-02 16:28
Yes, I agree. Btw, this code runs in NET Framework 4.8.
Is there a way I can override code in flush/refresh listeners?

**Comment by maca88** [comment] 2021-06-02 18:11
> Looks like regression from #2394

You are correct, the indexer should be used instead.

**Comment by igorvorona** [comment] 2021-06-02 18:29
@maca88 when can we get it fixed?

**Comment by maca88** [comment] 2021-06-02 19:34
After the fix (#2806) will be reviewed and merged you should be able to test it out by using the package from [myget](https://www.myget.org/gallery/nhibernate).

**Comment by igorvorona** [comment] 2021-06-02 19:55
Got it, thanks!

**Comment by igorvorona** [comment] 2021-06-03 21:55
I can only see a dev package 5.4.0-dev.3404
Is this the package that includes a fix for the issue #2806 ?

**Comment by hazzik** [comment] 2021-06-03 23:47
@igorvorona it is not yet merged.

**Comment by hazzik** [comment] 2021-06-03 23:55
@igorvorona it will be 5.3.9-dev.XXXX.

**Closed** 2021-06-04 12:12 UTC
Labels: Regression, c: Core, p: Minor, r: Fixed, t: Bug

**Comment by igorvorona** [comment] 2021-06-04 15:24
@hazzik any ETA when 5.3.9-dev.XXXX is available?
