### ISSUE TITLE
Add support for Dictionary<string, System.Type> in Component (Mapping-By-Code)

### ISSUE THREAD

**Issue by heikar** [nhibernate/nhibernate-core#2023] opened 2019-02-26 12:42 UTC
Hi :),

i have an issue with mapping a `IDictionary<string, object>` in Mapping-By-Code.
At the moment it looks like:
```
public class Template
{
public string Prop1 { get; set; }
public string Prop2 { get; set; }
}

Component<Template>(x => x.Details, new Template(), x => { ... });
```

Now my question: In the hbm mapping, i can at the runtime edit the properties and restart the application. Then the mapping for the `IDictionary<string, object>` is updated (e.g. add columns, remove columns). With Mapping-By-Code i cannot do this. Is it possible to change the second parameter to an `Dictionary<string, System.Type>` with which the developer can specify the columns:
```
var columns = new Dictionary<string, System.Type>();
columns.Add("Prop1", typeof(string));
columns.Add("Prop2", typeof(string));
Component(x => x.Details, columns, x => { ... });
```

What do you think about this solution?

Regards
heikar

**Comment by hazzik** [comment] 2019-02-26 22:06
Duplicate of #913

**Comment by hazzik** [comment] 2019-02-26 22:06
Thanks, we already have this feature request.

**Closed by hazzik** 2019-02-26 22:06 UTC
