### ISSUE TITLE
BinaryFormatter is not compatible with .Net8 runtime

### ISSUE THREAD

**Issue by dmitriyi-affinity** [nhibernate/nhibernate-core#3428] opened 2023-09-15 22:53 UTC
I have tried to port NHibernate to the .Net8 and fount the blocker in the SerializationHelper.cs class. It relies on the BinaryFormatter which is deprecated in .Net8

**Comment by hazzik** [comment] 2023-09-15 23:40
Duplicate of https://github.com/nhibernate/nhibernate-core/issues/2603

**Closed by hazzik** 2023-09-15 23:40 UTC

**Comment by fredericDelaporte** [comment] 2023-09-16 19:55
TLDR: review how your application works and eliminate any use of the binary serializer it does. NHibernate does not use it by itself, but only through the application choices, like mappings using `SerializableType`, uses of second level cache providers relying on binary serialization, ....
