### ISSUE TITLE
Lazy property with nosetter.pascalcase-underscore accessor remains uninitialized

### ISSUE THREAD

**Issue by sashakboo** [nhibernate/nhibernate-core#3333] opened 2023-06-21 07:24 UTC
In my project after upgrading from version 5.2 to 5.3 there is a problem with lazy properties that have nosetter.pascal-underscore accessor in their mapping.
- After accessing the property it remains uninitialized
- Each call to a property getter returns a new object

I have added tests which demonstrate the problem #3331

There is no such problem in version 5.2 #3332

**Comment by bahusoid** [comment] 2023-06-24 16:50
Most likely caused by #1943

**Comment by bahusoid** [comment] 2023-06-29 19:34
The 5.3.x+ lazy property implementation (#1943 and #1947) expects that both the getter and setter go through interception (https://github.com/nhibernate/nhibernate-core/blob/90d50c03475628d10336cbad368f071375056fef/src/NHibernate/Intercept/AbstractFieldInterceptor.cs#L101).

However, with field accessor, no interception occurs. This means that lazy property handling is broken in multiple places for `nosetter/field` lazy property accessors. In addition to the added test, the existing [CanMergeTransientWithLazyProperty](https://teamcity.jetbrains.com/buildConfiguration/bt7/4196655?buildTab=tests&status=failed&expandedTest=build%3A%28id%3A4196655%29%2Cid%3A2000003650) is also broken. I suspect that fetching such properties in a query would not work either.
																																					 
I took a quick look at how it is handled in [Hibernate](https://github.com/hibernate/hibernate-orm/commit/1e44e7420b7af10adc9547a461f02a6d979624f1) and it looks like they do not depend on interception (at least for property initialization, as I see multiple `attributeInitialized` calls).

See no easy fix for it.

**Comment by bahusoid** [comment] 2023-07-01 09:36
Fixed by #3345

**Closed by bahusoid** 2023-07-01 09:36 UTC
Labels: t: Bug, r: Fixed, c: Core, p: Minor, Regression
