### ISSUE TITLE
Property mapping with computed formula fails if SQL statement in formula includes a table-valued function with an alias.

### ISSUE THREAD

**Issue by spasecookee** [nhibernate/nhibernate-core#2733] opened 2021-04-19 21:35 UTC
The following HBM mapping works (as long as the table-valued function only returns a single column, anyway)
`        <property name="Blah">
          <formula>
            <![CDATA[ 
( SELECT * FROM dbo.Some_Table_Valued_Function(id) )
            ]]>
          </formula>
        </property>
`

Whereas this mapping does not
`        <property name="Blah">
          <formula>
            <![CDATA[ 
( SELECT TVF.ColA FROM dbo.Some_Table_Valued_Function(id) AS TVF )
            ]]>
          </formula>
        </property>
`

In the generated SQL the failure occurs because the second query produces SQL that looks something like 
`SELECT tableA0_.id, tableA0_.ColA  ( SELECT TVF.ColA FROM dbo.Some_Table_Valued_Function(tableA0_.id) AS tableA0_.TVF )  as formula0_0_  FROM tableA tableA0_   `

This is invalid SQL. The query engine seems to be adding the "tableA0_" prefix to the "TVF" alias that was provided for the function. The expected SQL statement should look like 

`SELECT tableA0_.id, , tableA0_.ColA  ( SELECT TVF.ColA FROM dbo.Some_Table_Valued_Function(tableA0_.id) AS TVF )  as formula0_0_  FROM tableA tableA0_   `

The reason this is an issue is that it's entirely possible that the table-valued function returns a column with the same name as the original table. Scalar-valued functions do not experience this issue, but NHibernate should still be able to work with table-valued functions, particularly given that the un-aliased version half-sorta works.

This is occurring with the SqlClientDriver and MsSql2012Dialect.

**Comment by bahusoid** [comment] 2021-04-20 10:24
Duplicate of https://github.com/nhibernate/nhibernate-core/issues/1247

**Closed by bahusoid** 2021-04-20 10:24 UTC
