### ISSUE TITLE
Too much memory usage issue

### ISSUE THREAD

**Issue by gokhanabatay** [nhibernate/nhibernate-core#2427] opened 2020-07-07 13:05 UTC
We are developing ***** system with nhibernate, our domain model has 900+ tables.
When we build session factory, sql command cache causes high memory usage issue.
Is there a way to tell NHibernate Lazy init all sql commands, when its needed?  
Maybe memory cache can be used for unused sql command cleanup?

Below memory dump was taken after first request.

![image](https://user-images.githubusercontent.com/9988911/86780421-6a8bd400-c065-11ea-99b2-d4aa3bbddd17.png)

![image](https://user-images.githubusercontent.com/9988911/86785661-a5910600-c06b-11ea-9c39-5247a7a1e35e.png)

Duplicate queries
![image](https://user-images.githubusercontent.com/9988911/86792592-52bb4c80-c073-11ea-9a4d-754f6750594f.png)

![image](https://user-images.githubusercontent.com/9988911/86781848-15e95880-c067-11ea-9f24-698648f03e1b.png)

![image](https://user-images.githubusercontent.com/9988911/86783223-b12efd80-c068-11ea-8a64-7436171f7b60.png)

**Comment by gokhanabatay** [comment] 2020-07-09 22:52
When using "default_batch_fetch_size" config its increases memory usage too much. Without "default_batch_fetch_size" results are acceptable.

![image](https://user-images.githubusercontent.com/9988911/87098344-b39f7c00-c24f-11ea-9e9d-83500fe5a297.png)

**Comment by hazzik** [comment] 2020-07-10 03:41
Yeah, we know. @gokhanabatay it was reported already.

Duplicate of #1316

Can you try "fix" in #1904?

**Closed by hazzik** 2020-07-10 03:41 UTC

**Comment by gokhanabatay** [comment] 2020-07-10 09:21
> Can you try "fix" in #1904?

"Agree. Better to optimize the code in batchers instead." you said in #1944 
Lazy sql initialization is not implemented, only choice is to remove global default_batch_fetch_size hibernate config file?
So we remove default_batch_fetch_size in config and result are posted at previous message.
Only merged pull request is #1942 reflection performance fix with default configuration bytecode-provider=lcg(default)  reflection-optimizer=true(default). 

@hazzik which fix, I can try right now?

**Comment by EngSayed** [comment] 2023-07-19 11:17
@hazzik, after adding "default_batch_fetch_size": 25 my application consumes double of the memory without using default batch size. I am not seeing a fix in #1904 
Could you please let us know how to fix this while having batches?

**Comment by bahusoid** [comment] 2023-07-19 11:35
See #2959

**Comment by EngSayed** [comment] 2023-07-19 11:52
> See #2959

Yes, I just found this one and about to test it but does it go with "default_batch_fetch_size" or only use "batch_fetch_style" ?
I am guessing both properties to set, right?

**Comment by fredericDelaporte** [comment] 2023-07-20 19:11
They do not control the same thing. batch fetch size controls the batch size, and disable batching if it is 1 or less, whatever the value of the fetch style. So, you still need to specify batch sizes if you want to use batching.

The style only changes the implementation used for batching, when batching is enabled.
