### ISSUE TITLE
Memory usage after initializing SessionFactory

### ISSUE THREAD

**Issue by danilosingh** [nhibernate/nhibernate-core#1933] opened 2018-12-08 11:36 UTC
We have a desktop application with 470 entities. The problem is that the application consumes more around 150MB in memory just when initializing the application, and of course this increases as the user uses. We have a long-term concern because this domain will grow.
We have clients that use Terminal Service, with many users, and our infrastructure reality in Brazil is precarious, which has generated problems of slowness in the system.
Is it possible to do something to decrease memory consumption at startup?
It would be great if Nhibernate created all the necessary configuration (loaders, proxies, sql strings) only in the first use of the entity, although this means to lose some performance in the first access.
Has anyone ever had this kind of problem? Do you know a strategy to improve?

**Comment by namer315** [comment] 2018-12-08 13:48
We have the same issue
is there any way to load entities per use only and have the ability dispose them later on
Thanks in advance

**Comment by danilosingh** [comment] 2018-12-08 15:43
@fredericDelaporte Could not this be optional?

**Comment by fredericDelaporte** [comment] 2020-01-05 17:01
In fact, duplicate of #1316.

**Closed by fredericDelaporte** 2020-01-05 17:01 UTC
Labels: c: Core, p: Minor, t: Improvement
